---

# hosts reference:
#[ucp-primary] ucp-manager1
#[ucp-replica] ucp-manager2 ucp-manager3
#[ucp-workers] ucp-worker1 ucp-worker2
#[dtr-primary] ucp-dtr1
#[dtr-replica] ucp-dtr2 ucp-dtr3

- hosts: all
  roles:
  - ntp
  - pre-deploy
  - docker-ee-install

- hosts: ucp-primary
  roles:
    - docker-ucp-primary

- hosts: ucp-replica
  serial: 1 # join managers one at a time
  roles:
    - docker-ucp-replica


# Join worker nodes of type: Node, DTR primary and replicas
- hosts: ucp-workers
  roles:
    - docker-ucp-worker

- hosts: dtr-primary dtr-replica
  serial: 1 # join UCP SWARM one at a time
  roles:
    - docker-dtr-joinswarm


## Install DTR primary (from UCP manager node)
#- hosts: ucp-primary
#  roles:
#    - docker-dtr-install

## Add DTR replicas
#- hosts: dtr-replica
#  serial: 1 # join DTR cluster one at a time
#  roles:
#    - docker-dtr-add-replicas

