---

# Setup docker storage
- stat: path=/etc/lvm/profile/docker-thinpool.profile
  register: thinpool_profile

- include: docker-storage.yml
  when: thinpool_profile.stat.exists == False


# Deploy docker-ee via docker store yum repo

- name: "Install libselinux-python to allow file copy"
  yum:
    name: libselinux-python
    state: present


# setup the repo

- name: "Create docker repo dockerurl yum vars"
  template:
    src: dockerurl.j2
    dest: /etc/yum/vars/dockerurl
    owner: root
    group: root

- name: "Add Docker yum repo"
  template: 
    src: docker-ee.repo.j2
    dest: /etc/yum.repos.d/docker-ee.repo
    owner: root
    group: root


# Add GPG key to rpm database

- name: "Add docker GPG key to RPM database"
  rpm_key:
    state: present
    key: "{{ docker_ee_url }}/gpg"


# Install docker-ee package

- name: "Install container-selinux package"
  yum:
    name: container-selinux
    update_cache: yes
    state: installed

- name: "Install Docker package"
  yum:
    name: docker-ee
    update_cache: yes
    state: installed

- name: "Ensure /etc/docker dir exists"
  file:
    path: /etc/docker
    state: directory


# Configure any daemon options 
- name: "Configure Docker engine"
  copy: 
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root


# devicemapper error device in use
- stat: path=/usr/lib/systemd/system/docker.service
  register: docker_service_config

- name: "Add MountFlags=slave to docker systemd service config"
  lineinfile:
    dest=/usr/lib/systemd/system/docker.service
    line="MountFlags{{ "=" }}slave"
    regexp="^MountFlags.*$"
    owner=root
    state=present
    insertafter="^Restart=on-failure"
  when: docker_service_config.stat.exists == True


- name: "Ensure docker engine is started" 
  systemd:
    name: docker
    state: started
    enabled: yes

- name: "Add centos user to docker group"
  user: name=centos groups=docker append=yes
