---

# Install DTR from Manager node

- debug:
   msg: "DTR Params: dtr-external-url: {{ dtr_external_fqdn }}, ucp-node: {{ hostvars[groups['ucp-primary'][0]]['ansible_eth0']['ipv4']['address'] }}, this-host: {{ fqdn }} dtr-primary-node: {{ hostvars[groups['dtr-primary'][0]]['ansible_fqdn']|quote }}"

- name: "Create DTR install script.."
  template:
    src: install-dtr-primary.sh.j2
    dest: /root/install-dtr-primary.sh
    owner: root
    group: root
    mode: 0755

- name: "Install the primary DTR node.."
  shell: /bin/sh /root/install-dtr-primary.sh {{ ucp_admin_username|quote }} {{ ucp_admin_password|quote }} 2>&1 | /usr/bin/tee -a /root/install-dtr-primary.log 
  args:
    creates: /root/install-dtr-primary.log


# Pause to allow DTR to finish initialising
#- pause:
#    minutes: 1


- name: "Obtain DTR Primary replica ID"
  shell: /usr/bin/curl -ksi https://{{ dtr_external_fqdn|quote }} | grep 'X-Replica-ID:' | awk '{print $2}'
  register: dtr_replica_id
  args:
    warn: false

- debug: 
    msg: "dtr_replica_id: {{ dtr_replica_id.stdout }}"


# Reconfigure for S3 storage (Note: this is broken in UCP 2.2.0 - needs to be done via GUI until fixed or new API available)
- name: "Reconfigure DTR primary to use S3 storage backend"
  template:
    src: reconfigure-dtr-storage.sh.j2
    dest: /root/reconfigure-dtr-storage.sh
    owner: root
    group: root
    mode: 0755

- shell: /bin/sh /root/reconfigure-dtr-storage.sh {{ ucp_admin_username|quote }} {{ ucp_admin_password|quote }} 2>&1 | /usr/bin/tee -a /root/reconfigure-dtr-storage.log 
  args:
    creates: /root/reconfigure-dtr-storage.log


