---

- name: "Obtain DTR Primary replica ID"
  shell: /usr/bin/curl -ksi https://{{ dtr_external_fqdn|quote }} | grep 'X-Replica-ID:' | awk '{print $2}'
  register: dtr_replica_id
  args:
    warn: false

- name: "Create DTR replica join script"
  template:
    src: dtr-replica-join.sh.j2
    dest: /root/dtr-replica-join.sh
    owner: root
    group: root
    mode: 0755

- name: "Adding DTR replica.."
  shell: /bin/sh /root/dtr-replica-join.sh {{ ucp_admin_username|quote }} {{ ucp_admin_password|quote }} 2>&1 | /usr/bin/tee -a /root/dtr-replica-join.log
  args:
    creates: /root/dtr-replica-join.log

